### ISSUE TITLE
.tmp directory not found on submit unit through web interface

### ISSUE THREAD

**Issue by Sovenger** [purpleworks/fleet-ui#11]
@subicura @jaehue When I try to create and submit a new unit through the web interface, I get this error in my docker log:

2015/03/02 20:34:54 submit unit
2015/03/02 20:34:54 err: stat ./tmp: no such file or directory
2015/03/02 20:34:54 Open file errpr: open ./tmp/apachetestservice.service: no such file or directory

Let me know if you need any other log output. Thanks.

**Comment by nballotta** [comment]
Same here! Why this happen?

**Comment by nballotta** [comment]
Ok, got it. The tmp directory on the docker image is missing. Workaround:

* Launch the Docker container
* `docker exec -it <CONTAINER ID> sh`
* `mkdir tmp`
* `exit`

After doing this, you may want to commit changes and save your image for future use.

**Comment by subicura** [comment]
oh, sorry! I'll fix it soon!
