### ISSUE TITLE
ETCD_PEER does not respect port

### ISSUE THREAD

**Issue by deitch** [purpleworks/fleet-ui#29]
I am running etcd 2.x, so the official IANA port of 2379 is in use. When I run fleet-ui, I pass it the `-e ETCD_PEER=a.b.c.d:2379` option.

However, if I `exec` into the running container and stub `/usr/local/bin/fleetctl`, I see that it tries to send it `fleetctl --endpoint http://172.30.20.160:2379:4001` (notice the appended `:4001`).

Ran purpleworks/fleet-ui:latest, image id is 165d50cf624b

**Comment by xuwang** [comment]
try ETCD_PEER=http://a.b.c.d:2379 format.

**Comment by deitch** [comment]
Thanks, I will try it now. Definitely should update the README.md under the "Getting Started" section

**Comment by deitch** [comment]
Nope. Then it adds the port *and* prepends http://

Debug output
`--endpoint http://http://127.0.0.1:2379:4001 list-units --full=true -l=true --fields=unit,load,active,sub,machine`

**Comment by xuwang** [comment]
The current source has fixed the bug but it is not in the current purpleworks/fleet-ui:latest image (165d50cf624b). 
You can either recompile fleet-ui and rebuild a new fleet-ui image with fix,  or as a workround, run etcd2 with
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
to get the default port 4001 working.

**Comment by deitch** [comment]
That would explain it. I will use the workaround for now. Any plans to push the fix to `latest`?

**Comment by xuwang** [comment]
@deitch you can pull the new image with the port fixes here: https://hub.docker.com/r/dockerage/fleet-ui/
It uses a forked xuwang/fleet-ui.git repo which contains wss socket fix (PR waiting) and more importantly, newer openssh-client cannot run in busybox image b/c missing shared libs. I switched to use debian:jessie which matches the base image I use to build the fleet-ui, resolving library issues. I tested, it works like so:
```
$ docker run -p 3000:3000 \
    -e ETCD_PEER=http://$COREOS_PRIVATE_IPV4:2379 \
    -v /home/core/.ssh/id_rsa_fleetui:/root/id_rsa"
```

**Comment by deitch** [comment]
Excellent. I will use that.

Is that the new official image? Or just a temporary fork?

**Comment by xuwang** [comment]
It's a temp fork. I don't own the official one.

**Comment by deitch** [comment]
Got it. Thanks @xuwang . I will leave this open until @purpleworks updates the image.

**Comment by subicura** [comment]
Thanks a lot @xuwang @deitch. We are now little busy, sorry for late. We'll update image as soon as possible!

**Comment by subicura** [comment]
finally, update image. Thank you.

**Comment by deitch** [comment]
Thanks @subicura
